$ErrorActionPreference = "Stop"

$projectRoot = $PSScriptRoot
$outputDirectory = Join-Path $projectRoot "dist"
$outputFile = Join-Path $outputDirectory "BezNigativa.lua"
$modules = [ordered]@{
    "App" = "src/App.lua"
    "core/Config" = "src/core/Config.lua"
    "core/Janitor" = "src/core/Janitor.lua"
    "ui/Window" = "src/ui/Window.lua"
    "features/Combat" = "src/features/Combat.lua"
    "features/Friends" = "src/features/Friends.lua"
    "features/Movement" = "src/features/Movement.lua"
    "features/Visuals" = "src/features/Visuals.lua"
    "features/Other" = "src/features/Other.lua"
    "games/Detector" = "src/games/Detector.lua"
    "games/RoleChams" = "src/games/RoleChams.lua"
    "games/Forsaken" = "src/games/Forsaken.lua"
    "games/MurderMystery2" = "src/games/MurderMystery2.lua"
    "games/AutoDodgeController" = "src/games/AutoDodgeController.lua"
    "games/UntitledBoxingGame" = "src/games/UntitledBoxingGame.lua"
}

$sources = [ordered]@{}
foreach ($entry in $modules.GetEnumerator()) {
    $path = Join-Path $projectRoot $entry.Value
    $sources[$entry.Key] = [IO.File]::ReadAllText($path)
}

$equals = "===="
while ($sources.Values.Where({ $_.Contains("]" + $equals + "]") }).Count -gt 0) {
    $equals += "="
}
$openBracket = "[" + $equals + "["
$closeBracket = "]" + $equals + "]"

$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine("-- BezNigativa v9.5 standalone bundle (generated by build.ps1)")
[void]$builder.AppendLine("local SOURCES = {")
foreach ($entry in $sources.GetEnumerator()) {
    [void]$builder.AppendLine("    [`"$($entry.Key)`"] = $openBracket")
    [void]$builder.Append($entry.Value)
    if (-not $entry.Value.EndsWith("`n")) { [void]$builder.AppendLine() }
    [void]$builder.AppendLine("$closeBracket,")
}
[void]$builder.AppendLine("}")
[void]$builder.AppendLine(@'

local cache = {}
local function loadModule(name)
    if cache[name] ~= nil then return cache[name] end
    local source = SOURCES[name]
    if not source then error("BezNigativa bundled module not found: " .. tostring(name)) end
    local compiler = loadstring or load
    if type(compiler) ~= "function" then error("Executor does not provide loadstring") end
    local chunk, compileError = compiler(source, "@BezNigativa/" .. name .. ".lua")
    if not chunk then error(compileError) end
    local result = chunk()
    cache[name] = result
    return result
end

return loadModule("App").start(loadModule)
'@)

[IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
$encoding = [Text.UTF8Encoding]::new($false)
$bundle = $builder.ToString()
[IO.File]::WriteAllText($outputFile, $bundle, $encoding)
Write-Output "Built $outputFile"
